Task_4-CORE: View a list of all articles
Sailynx-Zenefer/beeshine-news-fe pull request #2
Opened 2023-12-11 16:06 UTC by Sailynx-Zenefer

**Task_4-CORE: View a list of all articles**
- Sets up initial structure of app.
  - Creates Header and Nav components,which will be visible on all pages.
  - Creates main-page component, [ListArticlesView] on '/' which will be a list of all articles.
- Adds data fetching using axios to App.jsx to fetch article data and store it in state.
- Adds [ArticlesLister], a component that generates a list of [ArticleCards] from article data in state.
- Adds [ArticleCard], a component that uses article data in state, formats it and displays it.

2023-12-11 16:43 UTC, nc-kirsty-butterworth requested changes
really nice work so far 🚀 please extract your api and resubmit. Although you don't need to focus on your styling too much yet your Nav and Header components are taking up a lot of space on the page 👍

2023-12-11 16:43 UTC, nc-kirsty-butterworth commented on src/App.jsx
> +  },[])
this axios request should be in a separate utils file 👀

2023-12-12 13:45 UTC, nc-saleh commented
Looks good Willow! Axios does provide you with an easier way to handle the baseUrl of your api but if you have it working , then I am happy for you to carry on

2023-12-12 13:49 UTC, Sailynx-Zenefer commented
> Looks good Willow! Axios does provide you with an easier way to handle the baseUrl of your api but if you have it working , then I am happy for you to carry on

cheers. I'll merge and check that axios thing out then add it on the current commit i'm working on.

2023-12-12 13:50 UTC, merged